tap "hashicorp/tap"
tap "fluxcd/tap"

brew "kind"
brew "helm@3"
brew "helmfile"
brew "kubectl"
brew "watch"
brew "hashicorp/tap/vault"
brew "make"
brew "fish"
brew "tmux"
brew "fluxcd/tap/flux"
brew "koekeishiya/formulae/yabai"
brew "koekeishiya/formulae/skhd"
brew "fish-lsp"

cask "hammerspoon"
cask "proton-pass"
cask "ghostty"
cask "firefox"
cask "vscodium"
cask "slack"
cask "orbstack"
cask "spotify"
